name: Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: cachix/install-nix-action@v31.11.1
        with:
          extra_nix_config: |
            extra-substituters = https://cache.numtide.com
            extra-trusted-public-keys = niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=
      - run: nix flake check --print-build-logs
